language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --no-interaction

before_script:
  - mkdir -p tests/tmp/cache

script:
  - composer test

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php:
      - hhvm
